<?php
namespace grozzzny\base_module;

use Yii;
use yii\helpers\ArrayHelper;

class Module extends \yii\easyii\components\Module
{
    public $controllerNamespace = 'grozzzny\base_module\controllers';

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        static::registerAssets();
    }

    public static function registerAssets()
    {
        BaseModuleAsset::register(Yii::$app->view);
    }


    public function getModels()
    {
        $models = [];

        $settings = Yii::$app->getModule('admin')->activeModules[Yii::$app->controller->module->id]->settings;

        foreach (glob($this->basePath . "/models/*.php") as $file){
            $file_name = basename($file, '.php');

            if($file_name == 'Base') continue;

            $alternative_class_name = ArrayHelper::getValue($settings, 'model'.$file_name, '');

            $class_name = !empty($alternative_class_name) ? $alternative_class_name : preg_replace('/[^\\\]+$/', '', $this->className()) . 'models\\' . $file_name;

            if(!class_exists($class_name)) continue;

            $class = Yii::createObject($class_name);

            if(!$class::PRIMARY_MODEL) continue;

            $models[$class::SLUG] = $class;
        }

        return $models;
    }

    public function getModel($slug)
    {
        $models = $this->getModels();
        return empty($slug) ? current($models) : $models[$slug];
    }

}